### ISSUE TITLE
[BUG] When identifying an item the item picture remains the ?

### ISSUE THREAD

**Issue by tposney** [Forien/foundryvtt-forien-unidentified-items#1]
Any item I identify does not update the item picture, leaving it as s a question mark. If I peek at the item the picture is correct. Is this intended behaviour?
Love the module by the way.

**Comment by Forien** [comment]
It is not intended, and so far from what I tested it works just fine. Any console errors? Maybe some module conflict? :/ 

![](https://i.gyazo.com/13e8aef486e1caac008d998e64b53453.gif)

**Comment by Forien** [comment]
@tposney thanks to `Darshyne` on Discord I now know that the reason is VTTA Iconizer.

I'm yet to debug it, but from quick glance it looks like it pretty much disables ability to change the icon programmatically and I can't see override option.

**Comment by Forien** [comment]
@tposney possibly resolved in v0.1.4, can I ask you to confirm it?

**Comment by tposney** [comment]
Ha. Just spent a while chasing it down and came up with the same cause
which I was about to share.

**Comment by tposney** [comment]
It looks like it an issue with async updates. If I change identify to the following it works.
```
  static async identify(item) {
    const origData = item.getFlag(constants.moduleName, "origData");
    let hook = Hooks.call(`${constants.moduleName}:onIdentifyItem`, item, origData);
    if (hook !== false) {
      await item.update(origData);
      return item.unsetFlag(constants.moduleName, "origData");
    }
  }
```

**Comment by tposney** [comment]
Ha did not see the updated version note above. At least we came up with the same solution - lol.
