### ISSUE TITLE
Unidentified items do not retain system-specific data about weight/bulk/encumberance/quantity etc...

### ISSUE THREAD

**Issue by Talutha** [Forien/foundryvtt-forien-unidentified-items#5]
When mystifying an item in the Pathfinder2e system, the bulk amount is not retained in the unidentified item. When peeking or identifying, the bulk amount appears correctly.
![RJ0dGVKkGy](https://user-images.githubusercontent.com/11354522/85902643-24638480-b7ca-11ea-823f-860edffa6e5b.gif)

**Comment by Forien** [comment]
It's not a bug. 

Currently the module is **completely** system agnostic, so it doesn't retain **ANY** system specific data (like quantity, weight, encumberance, etc.). You can however, edit it freely to match. 

Support will be added in the future, either in this module itself, or by exposing API and allowing systems to define behaviour
